repos:
- repo: local
  hooks:
    - id: ruff
      name: ruff
      entry: ruff format --target-version=py311 --force-exclude
      language: python
      types_or: [python, pyi]
      require_serial: true
      additional_dependencies: []