site_name: Algorithm Selection Framework (ASF)
site_description: ASF is a powerful library for algorithm selection and performance prediction.
site_author: Hadar Shavit
site_url: https://hadarshavit.github.io/asf/
repo_url: https://github.com/hadarshavit/asf
repo_name: hadarshavit/asf
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: indigo
  # Add these SEO enhancements
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  favicon: docs/logo.jpg
  language: en

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quick_start.md
  - Advanced Features: 
    - Algorithm Selection Pipeline: features/algorithm_selection_pipeline.md
    - Hyperparameter Tuning: features/hyperparameter_tuning.md
    # - Algorithm Features: features/algorithm_features.md
    - Performance Prediction: features/performance_prediction.md
    - CLI: features/cli.md
  - API Reference:
      - Performance Prediction: api/epm.md
      - Metrics: api/metrics.md
      - Predictors: api/predictors.md
      - Preprocessing: api/preprocessing.md
      # - Presolving: api/presolving.md
      - Scenarios: api/scenario.md
      - Selectors: api/selectors.md
      - Utils: api/utils.md

extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-E4SDS0XQE5
  meta:
    - name: google-site-verification
      content: 7Gc5ioVEHE-L4FjTRDl3YjN_kRJ73w5wUE_bI_Yt6xg

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences