site_name: Algorithm Selection Framework (ASF)
site_description: ASF is a powerful library for algorithm selection and performance prediction.
site_author: Your Name
site_url: https://hadarshavit.github.io/asf/
site_keywords: ASF, algorithm selection, performance prediction, machine learning
theme:
  name: material

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Features: features.md
  - Quick Start: quick_start.md
  - Future Features: future_features.md
  - API Reference:
      - Selectors: api/selectors.md
      - Predictors: api/predictors.md
  - Installation: installation.md
  - Contributing: contributing.md
  - License: license.md

extra:
  version:
    provider: mike

google_analytics:
  - G-E4SDS0XQE5 #
  - auto
