name: Deploy MkDocs Documentation

on: 
    workflow_dispatch:
      
    release:
      types: [published]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git-based deployments with Mike
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python mike toml mkdocs-redirects
      - name: Extract version from pyproject.toml
        run: |
          python -c "
          import toml
          import os
          with open(os.environ['GITHUB_ENV'], 'a') as env:
            env.write(f\"VERSION={toml.load('pyproject.toml')['project']['version']}\n\")
          "
      - name: Deploy docs with Mike
        run: mike deploy --push --update-aliases ${{ env.VERSION }} latest
      - name: "Set default"
        run: mike set-default latest
